name: GitHub metrics as SVG image
on:
  schedule: [{cron: "0 22 * * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: mrBackSlash-it
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_pagespeed: yes
          plugin_languages: yes
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_playlist: https://open.spotify.com/embed/playlist/1HZmvRiTYROAwIeNnEunMU
